POST http://localhost:3000/app/v1/flight/admin/login
content-type: application/json

{
    "username": "mike", 
    "password": "mike"
}


###

POST http://localhost:3000/app/v1/airline/flight
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2UiLCJpYXQiOjE2NzE4NjczNzEsImV4cCI6MTY3MTk1Mzc3MX0.xNJ4alhcR6tc0T4SSG1-TAl3H073IpVAipxrH2Cg9sY
content-type: application/json

{

    "flight_number" : "ge789",

    "airline_id" : 2,

    "from_place" : "delhi",

    "to_place" : "pune",

    "start_time" : "17:00",

    "end_time" : "20:10",

    "total_number_of_business_class_seats" : "50",

    "total_number_of_nonbusiness_class_seats" : "50",

    "ticket_cost" : "5000",

    "total_number_of_seats" : "100",

    "meal" : "veg"

}

###

POST http://localhost:3000/app/v1/airline
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2UiLCJpYXQiOjE2NzE4NjczNzEsImV4cCI6MTY3MTk1Mzc3MX0.xNJ4alhcR6tc0T4SSG1-TAl3H073IpVAipxrH2Cg9sY
content-type: application/json

{
    "name" : "indigo"
}


###

PUT http://localhost:3000/app/v1/airline/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2UiLCJpYXQiOjE2NzE4NjczNzEsImV4cCI6MTY3MTk1Mzc3MX0.xNJ4alhcR6tc0T4SSG1-TAl3H073IpVAipxrH2Cg9sY
content-type: application/json

{
    "name" : "indigo",
    "blocked": "yes",
    "id": 1
}


###

GET http://localhost:3000/app/v1/flight/search
content-type: application/json

{
    "date": "23/02/2023",
    "from_place": "delhi",
    "to_place": "pune",
    "round_trip": "yes"
}

###

POST http://localhost:3000/app/v1/flight/booking/1
content-type: application/json

{

    "flight_id": 1,

    "booked_by": "mahesh",

    "email": "mahesh@gmail.com",

    "number_of_seats": 2,

    "passengers": [{"name": "suresh", "age":24, "gender":"male"}, {"name": "ramesh", "age":22, "gender":"male"}],

    "selected_meal": "veg",

    "selected_seat_number": null

}

###

GET http://localhost:3000/app/v1/flight/ticket/abc301

###

GET http://localhost:3000/app/v1/flight/booking/history/mahesh@gmail.com

###

PUT http://localhost:3000/app/v1/flight/booking/cancel/abc779

###

GET http://localhost:3000/app/v1/flights

###

GET http://localhost:3000/app/v1/join

###